#!/bin/bash
ln -sv ${PWD}/bash/bashrc ${HOME}/.bashrc
ln -sv ${PWD}/bash/local_bashrc ${HOME}/.local_bashrc
ln -sv ${PWD}/bash/aliases ${HOME}/.bash_aliases
ln -sv ${PWD}/bash/profile ${HOME}/.bash_profile
ln -sv ${PWD}/bash/logout ${HOME}/.bash_logout

ln -sv ${PWD}/readline_inputrc ${HOME}/.inputrc

ln -sv ${PWD}/gitconfig ${HOME}/.gitconfig
ln -sv ${PWD}/sshconfig ${HOME}/.ssh/config

ln -sv ${PWD}/nvim ${XDG_CONFIG_HOME}

mkdir -p ${HOME}/.gap
ln -sv ${PWD}/gap/gap.ini ${HOME}/.gap/gap.ini
ln -sv ${PWD}/gap/gaprc ${HOME}/.gap/gaprc
