#!/bin/bash
rm -v ~/.bashrc
rm -v ~/.bash_aliases
rm -v ~/.bash_profile
rm -v ~/.bash_logout

rm -v ~/.git-aware-prompt

rm -v ~/.inputrc

rm -vi ~/.gitconfig
rm -vi ~/.ssh/config

rm -vi ~/.gap/gap.ini
rm -vi ~/.gap/gaprc
