#!/bin/bash
# rsync options:
# a = archive,
# u = update,
# z = zip,
# --delete = deletes files that don't exist in source
# Useful to track moved files.
 rsync -azv --delete --exclude='.git' $HOME/uni/ momo:tux-uni
