#!/bin/bash
#
# start a vncserver (tigervnc) on emil and forward a port via ssh
# Arguments: $1=Displaynumber (optional)

PORT="${1-33}"
# Start the server on emil
ssh -T emil << ENDSSH
vncserver :"${PORT}"
ENDSSH
# Port forwarding via ssh, because vnc doesnt use encryption
ssh -fNL $((5900 + ${PORT})):localhost:$((5900 + ${PORT})) emil && \
    echo "Connect to the desktop via `localhost:$((5900 + ${PORT}))`"
