#!/bin/bash
# The GAP pkg JupyterKernel is used to run jupyter notebooks locally
export PATH=${PATH}:${HOME}/projects/pkg/JupyterKernel/bin/
# Make mouse slower: set "Constant Decelaration" of microsoft wireless mouse
# Apparently the device id (17) and property id for "Device Accel Constant
# Deceleration" (269).
# Devices and their properties:
# xinput --list
# xinput --list-props

# This is a bit ugly. We need to find device and properties IDs since they can
# change on reboot.
# grep the output of xinput --list
TMP=$(xinput --list | grep TouchPad)
# Remove *id= prefix
TMP=${TMP#*id=}
# Remove everything starting from the first whitespace
TMP=$(echo $TMP | sed 's/\s.*//g')
TOUCHPAD_ID=$TMP
# Do the same for "Microsoft Microsoft® 2.4GHz ..."
TMP=$(xinput --list | grep Microsoft)
TMP=${TMP#*id=}
TMP=$(echo $TMP | sed 's/\s.*//g')
WIRELESS_MOUSE_ID=$TMP
WIRELESS_MOUSE_ID_2=$((${WIRELESS_MOUSE_ID} + 1))
# And the same for "USB Optical Mouse"
TMP=$(xinput --list | grep 'USB Optical Mouse')
TMP=${TMP#*id=}
TMP=$(echo $TMP | sed 's/\s.*//g')
OPTICAL_MOUSE_ID=$TMP

# Properties
# grep the output of xinput --list-props
TMP=$(xinput --list-props $WIRELESS_MOUSE_ID | grep "Device Accel Profile")
# Remove prefix until ( and postfix from )
TMP=${TMP#*\(}
TMP=${TMP%\)*}
PROPERTY_ID_ACCEL_PROFILE=$TMP
PROPERTY_ID_CONSTANT_DECELERATION=$((${PROPERTY_ID_ACCEL_PROFILE} + 1))

# Settings
# turn off adaptive acceleration
xinput --set-prop ${TOUCHPAD_ID} ${PROPERTY_ID_ACCEL_PROFILE}                   0
xinput --set-prop ${TOUCHPAD_ID}                \
    ${PROPERTY_ID_CONSTANT_DECELERATION}        3.0
if [ $WIRELESS_MOUSE_ID ]; then
    xinput --set-prop ${WIRELESS_MOUSE_ID}      \
        ${PROPERTY_ID_CONSTANT_DECELERATION}    1.8
    xinput --set-prop ${WIRELESS_MOUSE_ID_2}      \
        ${PROPERTY_ID_CONSTANT_DECELERATION}    1.8
fi
if [ $OPTICAL_MOUSE_ID ]; then
    xinput --set-prop ${OPTICAL_MOUSE_ID}       \
        ${PROPERTY_ID_CONSTANT_DECELERATION}    3.7
fi
