#
# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enable extended globbing (expansion) to use patterns for case statements
shopt -s extglob
shopt -s globstar

# activate programmable bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# from github: jimeh/git-aware-prompt
export GITAWAREPROMPT=${HOME}/.myconfig/bash/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"

# from github: git/git/master/contrib/completion/git-completion.bash
export GITCOMPLETION=${HOME}/.myconfig/bash/git-completion.bash
source "${GITCOMPLETION}"

# add folders to PATH if not already contained
if ! [[ $PATH =~ ".local/bin" ]]; then
    export PATH=${PATH}:${HOME}/.local/bin
fi
if ! [[ $PATH =~ ".myconfig/scripts" ]]; then
    export PATH=${PATH}:${HOME}/.myconfig/scripts
fi

# Set vi mode
set -o vi
# Set neovim as EDITOR
export EDITOR="nvim"

# Prompt
# \w: show full dir stack
# \W: show only current dir
# if using \w only show top 2 dirs
export PROMPT_DIRTRIM=2
# @(..|..) is an extended globbing pattern which matches exactly one of the given pattens
HOSTNAMES_TO_IGNORE='@(f4d4889a99e9.ant.amazon.com|sergio-tux|duygu-xlaptop|sergio-kdesktop)'
case $HOSTNAME in
    $HOSTNAMES_TO_IGNORE )
        SHOW_HOSTNAME=''
        ;;
    * )
        SHOW_HOSTNAME='\[$txtred\]@\h'
        ;;
esac
# PS1='[\u@\h \w]\$ ' # default
PS1="\[\e[0;32m\]\u${SHOW_HOSTNAME}\[\e[m\] \[\e[0;34m\]\w\[\e[m\]"
PS1+=" \[$txtpur\]\$git_branch\[$txtred\]\$git_dirty\[\e[1;32m\]\$\[\e[m\] "
export PS1

# Disable C-Q and C-S hotkeys
stty -ixon

# Add alias definitions from .bash_aliases
if [ -f ~/.bash_aliases ]; then
        . ~/.bash_aliases
fi

# How many lines should the history keep? All of them.
export HISTFILESIZE=-1

# some XDG stuff?
export XDG_CONFIG_HOME="$HOME/.config"

# set TERM for neovim
export TERM="xterm-256color"

# Set Julia variable for where to search for packages
export JULIA_LOAD_PATH="$HOME/aktuell/symbolisches_rechnen/gitlab/:$JULIA_LOAD_PATH"

# Immediately write into history instead of only on exit
PROMPT_COMMAND="history -a"
# Change writing to history to "append-mode"
shopt -s histappend

# Load a file which handles quirks of the local system
if [ -f ~/.bashrc_local ]; then
        . ~/.bashrc_local
fi

if [ -f ~/.bash_text ]; then
        . ~/.bash_text
fi
if [ -f ~/.cargo/env ]; then
        . "$HOME/.cargo/env"
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
